version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - "./db-data:/var/lib/postgressql/data"
    ports:
      - "5433:5432"
